### ISSUE TITLE
Compilation issue on master

### ISSUE THREAD

**Issue by ncorrare** [oscam-emu/oscam-patched#47] opened 2019-05-13 18:11 UTC
Compiling with default options is currently failing
```
LINK	Distribution/oscam-1.20_svn11518-796-x86_64-redhat-linux.debug
build/x86_64-redhat-linux/module-emulator-biss.o: In function `biss_read_pem':
/usr/local/src/oscam-patched/module-emulator-biss.c:842: undefined reference to `PEM_read_RSAPrivateKey'
/usr/local/src/oscam-patched/module-emulator-biss.c:867: undefined reference to `i2d_RSA_PUBKEY'
/usr/local/src/oscam-patched/module-emulator-biss.c:876: undefined reference to `EVP_MD_CTX_new'
/usr/local/src/oscam-patched/module-emulator-biss.c:882: undefined reference to `EVP_sha256'
/usr/local/src/oscam-patched/module-emulator-biss.c:882: undefined reference to `EVP_DigestInit_ex'
/usr/local/src/oscam-patched/module-emulator-biss.c:883: undefined reference to `EVP_DigestUpdate'
/usr/local/src/oscam-patched/module-emulator-biss.c:884: undefined reference to `EVP_DigestFinal_ex'
/usr/local/src/oscam-patched/module-emulator-biss.c:885: undefined reference to `EVP_MD_CTX_free'
collect2: error: ld returned 1 exit status
```

**Comment by oscam-emu** [comment] 2019-05-13 18:45
Duplicate of #41, #43, #45.

You should run `make` with `USE_LIBCRYPTO=1` since a couple of releases now.

**Closed** 2019-05-13 18:46 UTC
Labels: question
